### ISSUE TITLE
C++ Release flags under different OS's

### ISSUE THREAD

**Issue by mhanus** [chi-tech/chi-tech#12]
When compiling on class01, I found out that the release flags used by CMake are `-O2 -DNDEBUG` rather than `-O3 -DNDEBUG` as on Mac or Ubuntu. As discussed in [this thread](http://cmake.3232098.n2.nabble.com/Default-CMAKE-C-FLAGS-value-by-OS-td7595064.html), it appears that Fedora is [specifically patching CMake](http://cmake.3232098.n2.nabble.com/Default-CMAKE-C-FLAGS-value-by-OS-tp7595064p7595070.html) to use `-O2` rather than `-O3` for Release builds (arguing that `-O3` is enabling some "dangerous" optimizations). On cluster, we have

```
[class01: ~/chi-tech] $ cat /etc/os-release
NAME="CentOS Linux"                        
VERSION="7 (Core)"                         
ID="centos"                                
ID_LIKE="rhel fedora"
...
```

so I suppose the last line shown is why. 

Now the question is &ndash; **do we want to force `CMAKE_CXX_FLAGS_RELEASE` to `-O3 -DNDEBUG`**? We could do that by simple string replace in CMakeLists.txt.

**Comment by wdhawkins** [comment]
I would vote for forcing -O3 until we have a
specific reason to downgrade to -O2 or, even
better, use -O3 and disable the specific
optimization that causes us problems.  I
have rarely seen issues with -O3, and, when it
has happened, it’s almost always been a
compiler issue.

— Daryl

On Sep 11, 2019, at 6:25 PM, mhanus <notifications@github.com<mailto:notifications@github.com>> wrote:


When compiling on class01, I found out that the release flags used by CMake are -O2 -DNDEBUG rather than -O3 -DNDEBUG as on Mac or Ubuntu. As discussed in this thread<https://urldefense.proofpoint.com/v2/url?u=http-3A__cmake.3232098.n2.nabble.com_Default-2DCMAKE-2DC-2DFLAGS-2Dvalue-2Dby-2DOS-2Dtd7595064.html&d=DwMFaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=AGGDkeGBg9rN2A12Ap4nyZd7ljYaFtmxn4Ih6xnU23U&m=-1i7erFOIsq-GfIE0gu3EPXXWSPMPRgoVsl1K971jOk&s=efXASiNQJ2H3fStfoiC6sicr28Temmx3YjNf25gsG4M&e=>, it appears that Fedora is specifically patching CMake<https://urldefense.proofpoint.com/v2/url?u=http-3A__cmake.3232098.n2.nabble.com_Default-2DCMAKE-2DC-2DFLAGS-2Dvalue-2Dby-2DOS-2Dtp7595064p7595070.html&d=DwMFaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=AGGDkeGBg9rN2A12Ap4nyZd7ljYaFtmxn4Ih6xnU23U&m=-1i7erFOIsq-GfIE0gu3EPXXWSPMPRgoVsl1K971jOk&s=W6PpXMKVrFvF_rSCYO13D2Jxc3rOh1Aazml6oFOYcs8&e=> to use -O2 rather than -O3 for Release builds (arguing that -O3 is enabling some "dangerous" optimizations). On cluster, we have

[class01: ~/chi-tech] $ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
...


so I suppose the last line shown is why.

Now the question is – do we want to force CMAKE_CXX_FLAGS_RELEASE to -O3? We could do that by simple string replace in CMakeLists.txt.

**Comment by mhanus** [comment]
> I would vote for forcing -O3 until we have a specific reason to downgrade to -O2 or, even better, use -O3 and disable the specific optimization that causes us problems. I have rarely seen issues with -O3, and, when it has happened, it’s almost always been a compiler issue. 

I agree with that. @Naktakala? (funny that {@}Jan here would notify some developer from Munich 😄)
