### ISSUE TITLE
Dependency building system

### ISSUE THREAD

**Issue by Naktakala** [chi-tech/chi-tech#17]
We need a system to automatically generate and build dependency

**Comment by gmovillanueva** [comment]
In regards to building external dependencies, if the dependency uses CMake, you can treat the dependency as an 'external project' and from within the ```CMakeLists.txt``` invoke the ```add_subdirectory()``` command to have the dependency compile with the project.

```cmake
if((NOT FOO_LIBRARY) OR (BAR_LIBRARY))  
  ...  
  # Lets build it!
  add_subdirectory(path/to/dir)
else() 
  ...
endif()
```
With that being said if the dependency uses a different build-system you can still treat it as an external project but instead of using ```add_subdirectory()``` you would use ```execute_process()```.  This can also be used to run a ```.configure```.

```cmake
if((NOT FOO_LIBRARY) OR (BAR_LIBRARY))
  ...
  # Lets build it!
  execute_process(make -G... -O3... /path/to/dir)
else()
  ...
endif()
```

A minor recommendation to avoid cluttering the main ```CMakeLists.txt```, another ```CMakelists.txt``` can be written and then called from the main ```CMakelists.txt```.

**Comment by Naktakala** [comment]
A python script has been built that can serve our efforts for now. See pull request #20

**Comment by Naktakala** [comment]
The python script largely works. It's not perfect but it does the job in >80% of the cases.
