### ISSUE TITLE
Use of MPI_barrier

### ISSUE THREAD

**Issue by wdhawkins** [chi-tech/chi-tech#171]
MPI_barrier should be used judiciously.  We need to examine all use cases and eliminate barriers that are not strictly needed.

**Comment by Naktakala** [comment]
I am closing this issue. I've used it as a general "be mindful" comment ever since it has been created. Since then, MPI_Barriers have been propping up and torn down all over the place as I've looked at bugs, profiled or investigated something. 

The real solution is apparent: The production viability of the code-base on >1000 processors needs to be assessed based on rigorous testing at those kind of core counts. During such a process the true costs of the barriers will reveal themselves. 

Currently we do not have the resources to do this testing and the barriers offer "training-wheels" for catching bugs so I am discontinuing this as an issue to be addressed.
