### ISSUE TITLE
Transport Cross-section naming of precursor yields

### ISSUE THREAD

**Issue by Naktakala** [chi-tech/chi-tech#270]
There are some precursor input improvements planned so we can punt problems to this issue.

**Comment by zachhardy** [comment]
Any thoughts on this? I have a few ideas:

1. Use a struct to describe each precursor. It *feels* better to include the emission spectra, but this could slow the code down slightly. Currently, `chi_delayed` is accessed first by group, the by precursor index (the order of the looping in the code). Going the other way will certainly be slower if we keep the same loop structure. The alternative is to handle delayed neutrons external to the main loop of groups and to loop over precursors, destination groups, then source groups.
  ```
  struct Precursor 
  {
         double decay_constant;
         double fractional_yield;  //or yield_fraction
         std::vector<double> emission_sprectra;  //maybe
   };
  ```

2. Remove `precursor_yield` in favor of scaling the emission spectra by those values. Why remove this? The alternative I listed is exactly how NJOY specifies the delayed spectra. The definition of `chi_delayed` would then be $\sum_g \chi^d_{g,j} = \gamma_j$, and $\sum_j \gamma_j = 1$, and $\sum_j \sum_g \chi^d_{g,j} = 1$. The downfall to this strategy is that it will be slightly more expensive to compute precursor updates. This, however, is not done often.

3. The easiest solution is to simply change `precursor_yield` to `precursor_yield_fraction` and leave everything else the same.

4. We could change `precursor_lambda` to either `decay_constants` or `precursor_decay_constants`. When this was first implemented, we did not want to use `decay_constants` because there could be confusion about whether it is a decay constant for the material or precursors.

Thoughts?

**Comment by ragusa** [comment]
1.  I'm fine to keep it as is for now. But tell me the lines I need to look at where you think a rework would be beneficial.
  2.  Same. Point me to the lines you recommend I look at. When I reviewed a recent PR, I remember that I was at first baffled by what the precursor yield was. Actually, it was that piece of code:
***@***.***

But I understand now I was expecting beta[g][j] and you are telling me that the yield is more naturally including in chi_delayed. So, I am not sure at this point. Maybe better to discuss live.

  1.  Likely ok with me
  2.  I think that if we ever make it to a point where a material decays, then we could discuss. I am not sure there will be a confusion as of whether one is dealing with a material or a delayed n precursor. I am in favor of decay_constant as it is more explicit. Whether you add precursor in front of it or not, I'd say no for now but I'm flexible.

**Comment by zachhardy** [comment]
I think I agree that this would be best discussed live. There are a number of issues we should hammer out:

1. The notation we use, particularly for precursors,
2. Which attributes should stay and which should go (particularly when moving to a production matrix)
3. What fission configurations default to (primarily concerned about specifying prompt/delayed, but then turning off precursors).

I think things are getting clunky and we could use a more clean implementation.
