### ISSUE TITLE
Remove -fpermissive

### ISSUE THREAD

**Issue by mhanus** [chi-tech/chi-tech#7]
We should remove the flag `fpermissive` from the list of our compilation flags. If errors occur, we should fix them rather than downgrading to warnings (of course, provided the error doesn't come from a TPL (but then we should mention that `fpermissive` is needed just because this or that library).

**Comment by wdhawkins** [comment]
My patch includes that fix.

— Daryl

On Sep 6, 2019, at 11:36 PM, mhanus <notifications@github.com<mailto:notifications@github.com>> wrote:


We should remove the flag fpermissive from the list of our compilation flags. If errors occur, we should fix them rather than downgrading to warnings (of course, provided the error doesn't come from a TPL (but then we should mention that fpermissive is needed just because this or that library).

**Comment by Naktakala** [comment]
When it is removed ... what code needs to change? Also why is it there? I can't remember

**Comment by wdhawkins** [comment]
After removing it, I don’t think I had to change any code.  Whatever it was added for must have been fixed or removed.

— Daryl

On Sep 8, 2019, at 6:53 PM, NikTheNak <notifications@github.com<mailto:notifications@github.com>> wrote:


When it is removed ... what code needs to change? Also why is it there? I can't remember

**Comment by Naktakala** [comment]
This has been fixed in PR #10
